apiVersion: v1
kind: Pod
metadata:
  name: wttr-proxied
  labels:
    app.kubernetes.io/name: wttr-app-proxied
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  initContainers:
  - name: mitmproxy
    image: mitmproxy/mitmproxy
    restartPolicy: Always
    command: ["mitmweb", "--listen-port", "9080", "--web-port", "9081"]
    ports:
      - containerPort: 9080
        name: mitmproxy-port
      - containerPort: 9081
        name: mitmweb-port
    volumeMounts:
    - name: shared-data
      mountPath: /root/.mitmproxy
  containers:
  - name: wttr
    image: wttr-proxied:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: http_proxy
      value: localhost:9080
    - name: https_proxy
      value: localhost:9080
    ports:
      - containerPort: 8080
        name: wttr-port
    volumeMounts:
    - name: shared-data
      mountPath: /etc/ssl/certs

---
apiVersion: v1
kind: Service
metadata:
  name: wttr-service-proxied
spec:
  selector:
    app.kubernetes.io/name: wttr-app-proxied
  ports:
  - name: wttr-svc-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: mitmproxy-svc-port
    protocol: TCP
    port: 9080
    targetPort: 9080
  - name: mitmweb-svc-port
    protocol: TCP
    port: 9081
    targetPort: 9081
